config/routes.rb
Rails.application.routes.draw do
  resources :bills
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:client, :client_order, :cost)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/bills/_form.html.erb
<%= form_for(bill) do |f| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client %>
    <%= f.text_field :client %>
  </div>

  <div class="field">
    <%= f.label :client_order %>
    <%= f.text_field :client_order %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>
CARNEFRANGOEQUEIJON - PASTELARIA
<h1>Bills</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Client order</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.client %></td>
        <td><%= bill.client_order %></td>
        <td><%= bill.cost %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @bill.client %>
</p>

<p>
  <strong>Client order:</strong>
  <%= @bill.client_order %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @bill.cost %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>
CARNEFRANGOEQUEIJON - PASTELARIA
<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.amount %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @client.amount %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carnefrangoequeijon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>